# Generated by Django 5.1.3 on 2024-12-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ticket_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
