# Generated by Django 5.1.3 on 2025-03-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='massage',
            field=models.TextField(verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='نوع درخواست'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('body', models.TextField(verbose_name='متن کامنت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('activ', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_commen_created_79f39f_idx')],
            },
        ),
    ]
