# Generated by Django 5.1.3 on 2025-04-17 04:13

import blog.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_image_image_field_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to=blog.models.get_image_upload_to, verbose_name='تصویر'),
        ),
    ]
